### ISSUE TITLE
CRASH + LEAKS

### ISSUE THREAD

**Issue by sabitbol42** [tdameros/42-minishell#3]
Hello, 
while testing some functionalities i noticed few problems and a crash: 
```
echo /*/*/*/*/*/*/*/*/*/* into ctrl + C = crash
```
also simple wildcard doesnt works as expected such as : 

```abc*abc*abc ```

**Comment by tdameros** [comment]
Matching detection with wildcards involves 2-3 design errors.
However, we just need to correct the function that indicates whether there is a match or not:

https://github.com/tdameros/42-minishell/blob/main/src/expansions/wildcards/match.c
